# Generated by Django 4.1.5 on 2023-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="Product Name")),
                ("brand", models.CharField(max_length=255, verbose_name="Brand")),
                ("price", models.FloatField(default=0, verbose_name="Price")),
            ],
        ),
    ]
